plugin: gcp_compute
projects:
  - infra-235410
filters:
auth_kind: serviceaccount
service_account_file: ./dynamic/service-account.json

keyed_groups:
  - key: labels.ansible_group
hostnames:
  # List hosts by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_private_host: networkInterfaces[0].networkIP
