---
- name: Configure App
#  hosts: app
  hosts: reddit-app
  become: true
  vars:
#    db_host: 10.132.0.48
#    db_host: "{{ reddit-db.networkInterfaces[0].networkIP }}"
#    db_host: "{{ hostvars['reddit-db']['ansible_default_ipv4']['address'] }}"
    db_host: "{{ hostvars['reddit-db']['ansible_private_host'] }}"
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
